spring:
  data:
    # https://tothis.gitee.io/mongodb/mongo/install
    mongodb:
      host: 192.168.81.129
      database: admin
      port: 27017
      username: test
      # 需加引号
      password: '123456'